version: '3'

services:
  app1:
    build: ./app1
    ports:
      - "8001:8000"
    depends_on:
      - app2
    networks:
      - container_network
    container_name: containerA-app1

  app2:
    build: ./app2
    ports:
      - "8002:8000"
    networks:
      - container_network
    container_name: containerA-app2

networks:
  container_network:
    driver: bridge
