version: "3.8"

services:
  app1:
    build:
      context: ./app1
    ports:
      - "8001:8000"
    depends_on:
      - app2

  app2:
    build:
      context: ./app2
    ports:
      - "8002:8000"
